### ISSUE TITLE
Use collective.indexing?

### ISSUE THREAD

**Issue by gforcada** [collective/collective.elasticsearch#10]
Although here at the Alpine City Sprint we are assimilating collective.indexing into Plone core itself, I was surprised to see that c.elasticsearch is monkey patching all CMFPlone search/index related methods as a way to hook into the catalog machinery.

With @MrTango we are working on a PLIP for that, but as any PLIP it will take its time...

**Comment by jensens** [comment]
FYI: PLIP was merged in Plone 5.1

**Comment by gforcada** [comment]
They are probably fine without 😄
