### ISSUE TITLE
ElasticSearchCatalog._default_mapping usage

### ISSUE THREAD

**Issue by tdesvenain** [collective/collective.elasticsearch#19]
is ElasticSearchCatalog._default_mapping actually used ? how ?

https://github.com/collective/collective.elasticsearch/blob/master/collective/elasticsearch/es.py#L76

**Comment by vangheem** [comment]
If you delete Title, SearchableText, Description, it won't know how to define those without this I believe.

**Comment by tdesvenain** [comment]
This is done by 
MappingAdapter._default_mapping, isn't it ?
https://github.com/collective/collective.elasticsearch/blob/master/collective/elasticsearch/mapping.py#L9

**Comment by vangheem** [comment]
Yes.

**Comment by tdesvenain** [comment]
ok so ElasticSearchCatalog._default_mapping is dead code, only MappingAdapter._default_mapping is really used ?

**Comment by vangheem** [comment]
Yes.
