### ISSUE TITLE
How to avoid a log from elasticsearch python module

### ISSUE THREAD

**Issue by tdesvenain** [collective/collective.elasticsearch#21]
Hi, I'm afraid that all my zope instances's log files will be polluted by elasticsearch python module logs,
which log at info level each successful query...
@vangheem did you find a way to prevent this ?

**Comment by vangheem** [comment]
I believe the elasticsearch module uses "info" log level. You can modify your zope config to change logging level: https://pypi.python.org/pypi/plone.recipe.zope2instance
