### ISSUE TITLE
Server Status in control panel does not display any info

### ISSUE THREAD

**Issue by fulv** [collective/collective.elasticsearch#39]
This is due to a bug in https://github.com/collective/collective.elasticsearch/blob/master/collective/elasticsearch/browser/controlpanel.py#L57:

    ('Size', str(int(math.ceil(size_in_mb) + 'MB'))),

which causes a `TypeError: "unsupported operand type(s) for +: 'float' and 'str'"`.
Subsequently, this error is swallowed by the `except` on the next line.

**Comment by fulv** [comment]
Yeah, that's what my PR does.  I just opened the issue to document the
change.

**Comment by wohnlice** [comment]
Yeah, I realized that as soon as I posted the comment, so I deleted it. You caught me ;)
