### ISSUE TITLE
Path index

### ISSUE THREAD

**Issue by maartenkling** [collective/collective.elasticsearch#7]
When using the navigation portlet the result is different

in catalog path returned is different from es

['folder2', 'page5', 'page3', 'folder1', 'page6', 'folder3', 'page1', 'page2', 'page4']
(Pdb) [x.id for x in self.searchResults(path={'query': '/plone/folder1', 'navtree_start': 0, 'navtree': 1}, is_default_page=False)]
['folder1', 'page1', 'page2', 'page3', 'folder2']
(Pdb) [x.id for x in self.searchResults(path={'query': '/plone/folder1', 'navtree_start': 0, 'navtree': 1}, is_default_page=False)]
['folder1', 'page1', 'page2', 'page3', 'folder2']
(Pdb) [x.id for x in self.catalog(path={'query': '/plone/folder1', 'navtree_start': 1, 'navtree': 1}, is_default_page=False)]
['folder2', 'page5', 'page3', 'page6', 'folder3', 'page1', 'page2', 'page4']
(Pdb) [x.id for x in self.searchResults(path={'query': '/plone/folder1', 'navtree_start': 1, 'navtree': 1}, is_default_page=False)]
['folder1', 'page1', 'page2', 'page3', 'folder2']
(Pdb) [x.id for x in self.searchResults(path={'query': '/plone/folder1', 'navtree_start': 2, 'navtree': 1}, is_default_page=False)]
['page1', 'page2', 'page3', 'folder2']
(Pdb) [x.id for x in self.catalog(path={'query': '/plone/folder1', 'navtree_start': 2, 'navtree': 1}, is_default_page=False)]
['page5', 'page6', 'folder3', 'page4']
(Pdb) [x.id for x in self.searchResults(path={'query': '/plone/folder1', 'navtree_start': 1, 'navtree': 1}, is_default_page=False)]
['folder1', 'page1', 'page2', 'page3', 'folder2']
(Pdb) [x.id for x in self.catalog(path={'query': '/plone/folder1', 'navtree_start': 1, 'navtree': 1}, is_default_page=False)]
['folder2', 'page5', 'page3', 'page6', 'folder3', 'page1', 'page2', 'page4']

**Comment by vangheem** [comment]
I just merged my branch that only uses elasticsearch for full text queries so this should not happen anymore.

**Comment by maartenkling** [comment]
nice!
